query GetUsers {
  allUsers {
    id
    firstName
    lastName
    email
    role
    createdAt
    updatedAt
    name
  }
}

query GetUser {
  user(id: 2) {
    id
    firstName
    lastName
    email
    role
    createdAt
    updatedAt
    name
  }
}

mutation registerUser {
  registerUser(user: {
      firstName: "Jone"
      lastName: "Doe"
      email:"example@test.com"
      password:"1234"
      role:"manager"
    }) {
      id
      name
      role
    }
}